export const LOADED_DIALECTS = "LOADED_DIALECTS";
export const COMPLETED_GRAMMARS = "COMPLETED_GRAMMARS";
export const SELECTED_GRAMMAR = "SELECTED_GRAMMAR";
export const SIGNIN = "SIGNIN";
export const SIGNUP = "SIGNUP";
export const SIGNOUT = "SIGNOUT";
